
.PHONY: all clean instlink buffer memcpu refinedmemcpu

all: instlink buffer memcpu refinedmemcpu

clean:
	$(MAKE) -C instlink clean
	$(MAKE) -C buffer clean
	$(MAKE) -C memcpu clean
	$(MAKE) -C refinedmemcpu clean


instlink:
	$(MAKE) -C instlink

buffer:
	$(MAKE) -C buffer

memcpu:
	$(MAKE) -C memcpu

refinedmemcpu:
	$(MAKE) -C refinedmemcpu

